pipelines A-z col transformer

In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
df = pd.read_csv(r'C:\Basic_Datascience_4ML\assets\data\covid_toy.csv')
df.sample(10)

age  gender     fever   cough       city has_covid
14   51    Male 104.00000    Mild  Bangalore        No
45   72    Male  99.00000    Mild  Bangalore        No
42   27    Male 100.00000    Mild      Delhi       Yes
15   70    Male 103.00000  Strong    Kolkata       Yes
84   69  Female  98.00000  Strong     Mumbai        No
19   42  Female       NaN  Strong  Bangalore       Yes
68   54  Female 104.00000  Strong    Kolkata        No
76   80    Male 100.00000    Mild  Bangalore       Yes
24   13  Female 100.00000  Strong    Kolkata        No
35   82  Female 102.00000  Strong  Bangalore        No

In [73]:
df.value_counts('cough')

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [67]:
df.count()

age          100
gender       100
fever         90
cough        100
city         100
has_covid    100
dtype: int64

In [68]:
df.describe()

age     fever
count 100.00000  90.00000
mean   44.22000 100.84444
std    24.87893   2.05493
min     5.00000  98.00000
25%    20.00000  99.00000
50%    45.00000 101.00000
75%    66.50000 102.75000
max    84.00000 104.00000

In [69]:
df.isnull().sum()


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

split the Data first

In [84]:
from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df[['has_covid']],test_size=0.2)
X_train['fever']

38   101.00000
65   102.00000
84    98.00000
37   100.00000
86   104.00000
        ...   
53    98.00000
68   104.00000
47   104.00000
45    99.00000
35   102.00000
Name: fever, Length: 80, dtype: float64

In [71]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_imputed = si.fit_transform(X_train[['fever']]) # use double [[]] to pass single col as 2D frame and sklearn only take 2D frame
X_test_imputed = si.transform(X_test[['fever']])
np.ndim(X_train_imputed)
print(X_train_imputed)

[[ 99.        ]
 [103.        ]
 [ 98.        ]
 [100.        ]
 [104.        ]
 [ 99.        ]
 [102.        ]
 [104.        ]
 [100.        ]
 [102.        ]
 [ 98.        ]
 [101.        ]
 [104.        ]
 [ 98.        ]
 [ 98.        ]
 [100.90140845]
 [100.90140845]
 [ 99.        ]
 [104.        ]
 [ 99.        ]
 [ 99.        ]
 [101.        ]
 [100.90140845]
 [102.        ]
 [100.90140845]
 [101.        ]
 [100.90140845]
 [ 98.        ]
 [ 98.        ]
 [ 98.        ]
 [102.        ]
 [104.        ]
 [101.        ]
 [ 99.        ]
 [103.        ]
 [101.        ]
 [104.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [102.        ]
 [103.        ]
 [102.        ]
 [ 99.        ]
 [ 98.        ]
 [100.90140845]
 [ 98.        ]
 [100.90140845]
 [101.        ]
 [104.        ]
 [101.        ]
 [ 99.        ]
 [104.        ]
 [102.        ]
 [101.        ]
 [102.        ]
 [104.        ]
 [ 98.        ]
 [101.        ]
 [ 99.        ]
 [ 98.        ]
 [100.90140845]
 [103.  

ordinal encoding

In [75]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_Encoded = oe.fit_transform(X_train[['cough']])
X_test_Encoded = oe.transform(X_test[['cough']])
print(X_train_Encoded)

[[1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]]


In [76]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_Encoded = ohe.fit_transform(X_train[['gender','city']])
X_test_Encoded = ohe.transform(X_test[['gender','city']])
print(X_train_Encoded)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0.

In [80]:
df.nunique()

age          55
gender        2
fever         7
cough         2
city          4
has_covid     2
dtype: int64

we can automate all above steps just by using sklearn.compose
-------------------------------------------------------------------

In [89]:

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

# Define transformer
ct = ColumnTransformer(transformers=[
    ('fever_imputer', SimpleImputer(strategy='constant', fill_value=0), ['fever']),
    ('cough_encoder', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('ohe', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
], remainder='passthrough')

# Fit and transform training data
X_train_transformed = ct.fit_transform(X_train)

# Transform test data
X_test_transformed = ct.transform(X_test)

print(X_train_transformed)


[[101.   0.   0.   1.   0.   0.  49.]
 [102.   0.   0.   0.   0.   0.  69.]
 [ 98.   1.   0.   0.   0.   1.  69.]
 [100.   0.   1.   0.   1.   0.  55.]
 [104.   0.   1.   0.   0.   0.  25.]
 [104.   0.   1.   0.   0.   0.  51.]
 [102.   0.   1.   0.   0.   0.  64.]
 [101.   0.   0.   0.   0.   1.  81.]
 [100.   0.   0.   0.   1.   0.   5.]
 [101.   0.   0.   0.   0.   0.  20.]
 [102.   1.   0.   0.   0.   0.  24.]
 [104.   0.   0.   0.   0.   0.  12.]
 [102.   1.   1.   1.   0.   0.  20.]
 [  0.   0.   1.   1.   0.   0.  38.]
 [104.   1.   0.   1.   0.   0.  75.]
 [103.   0.   1.   0.   1.   0.  83.]
 [104.   0.   1.   0.   1.   0.  16.]
 [ 98.   1.   0.   0.   0.   1.  81.]
 [102.   0.   0.   1.   0.   0.  49.]
 [101.   1.   0.   1.   0.   0.  68.]
 [  0.   1.   0.   0.   0.   1.  34.]
 [  0.   1.   0.   0.   0.   1.  20.]
 [104.   1.   0.   1.   0.   0.  34.]
 [100.   0.   0.   0.   1.   0.  19.]
 [100.   1.   0.   0.   0.   0.  47.]
 [  0.   0.   0.   1.   0.   0.  75.]
 [101.   0. 