Numpy_4Everyone

In [ ]:
import numpy as np

Creating array from list

In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)

  Difference btw normal array and np array
Feature             | Python List                | NumPy Array
--------------------|----------------------------|----------------------------
Type                | Heterogeneous (mixed types)| Homogeneous (same type)
Performance         | Slower (pure Python loop)  | Faster (C-optimized)
Memory Usage        | More memory                | Less memory
Math Operations     | Not supported directly     | Element-wise supported
Indexing            | Basic indexing/slicing     | Advanced indexing/slicing
Broadcasting        | Not supported              | Supported
Multi-dimensional   | Needs nesting              | Built-in multi-dimensional
Best For            | Small, mixed-type data     | Large numeric data, ML/DL


In [ ]:
import numpy as np
import time


# --- Multiply elements by 2 in a Python list ---
start = time.time()
py_list = [1, 2, 3, 4, 5]
py_list_result = [x * 2 for x in py_list]
end = time.time()
print(f"Python list time: {end - start:.5f} seconds")

# --- Multiply elements by 2 in a NumPy array ---
start = time.time()
np_array = np.array([1, 2, 3, 4, 5])
np_array_result = np_array * 2
end = time.time()
print(f"NumPy array time: {end - start:.5f} seconds")


# Python list
py_list = [1, 2, 3, 4, 5]
print("Python list result:", py_list*2)

py_list_result = list(map(lambda x: x * 2,py_list))
print(py_list_result)


# NumPy array vector element
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy array result:", np_array*2)



Types of build it method to make array

In [ ]:
import numpy as np

# 1️⃣ From a Python list or tuple
arr_from_list = np.array([1, 2, 3, 4, 5])
arr_from_tuple = np.array((6, 7, 8, 9, 10))

# 2️⃣ Arrays of zeros, ones, empty values
zeros_arr = np.zeros((3, 3))     # 3x3 matrix of zeros
ones_arr = np.ones((2, 4))       # 2x4 matrix of ones
empty_arr = np.empty((2, 3))     # uninitialized (fast but random data)

# 3️⃣ Identity matrix
identity_arr = np.eye(4)         # 4x4 identity

# 4️⃣ Arrays with a range of values
range_arr = np.arange(0, 10, 2)  # start=0, stop=10, step=2
linspace_arr = np.linspace(0, 1, 5)  # 5 equally spaced numbers from 0 to 1

# 5️⃣ Constant value arrays
full_arr = np.full((3, 3), 7)    # 3x3 matrix filled with 7

# 6️⃣ Random arrays
rand_arr = np.random.rand(2, 3)  # uniform [0,1)
randn_arr = np.random.randn(3, 3) # normal distribution
randint_arr = np.random.randint(1, 10, (3, 3))  # integers [1,10)

# 7️⃣ Complex numbers
complex_arr = np.array([1+2j, 3+4j])

# 8️⃣ Boolean arrays
bool_arr = np.array([True, False, True])

# 9️⃣ Diagonal matrix
diag_arr = np.diag([1, 2, 3, 4])

# 🔟 Reshaped array
reshaped_arr = np.arange(1, 13).reshape(3, 4)  # 3x4 matrix

# Print examples
print("From list:", arr_from_list)
print("Zeros:\n", zeros_arr)
print("Identity:\n", identity_arr)
print("Range:", range_arr)
print("Linspace:", linspace_arr)
print("Random:\n", rand_arr)
print("Diagonal:\n", diag_arr)
print("Reshaped:\n", reshaped_arr)


Dim of array

Type        | Shape             | Use
------------|-------------------|-----------------------------------
Scalar      | ()                | Learning rate
Vector      | (300,)            | Word embeddings
Matrix      | (28,28)           | Grayscale image
3D Tensor   | (3,224,224)       | RGB image / NLP seq
4D Tensor   | (32,3,224,224)    | Batch of RGB images
Higher      | (batch,seq,feat,…)| Advanced NLP / multi-modal


In [ ]:
import numpy as np

# Scalar (0D)
scalar = np.array(42)
print("Scalar:", scalar, "Shape:", scalar.shape)

# Vector (1D)
vector = np.array([1, 2, 3])
print("\nVector:\n", vector, "Shape:", vector.shape)

# Matrix (2D)
matrix = np.array([[1, 2], [3, 4]])
print("\nMatrix:\n", matrix, "Shape:", matrix.shape)

# 3D Tensor (Channels x Height x Width)
tensor_3d = np.random.rand(3, 4, 4)  # small RGB-like image
print("\n3D Tensor:\n", tensor_3d, "Shape:", tensor_3d.shape)

# 4D Tensor (Batch x Channels x Height x Width)
tensor_4d = np.random.rand(2, 3, 4, 4)  # batch of RGB images
print("\n4D Tensor:\n", tensor_4d, "Shape:", tensor_4d.shape)

# Higher-order Tensor (Batch x Seq_len x Features)
tensor_high = np.random.rand(2, 5, 10)  # batch of sequences with features
print("\nHigher Tensor:\n", tensor_high, "Shape:", tensor_high.shape)


Array Property
Property    | Description                                  | Example Output
------------|----------------------------------------------|---------------
.ndim       | Number of dimensions                         | 2
.shape      | Dimensions as a tuple (rows, cols, …)        | (3, 4)
.size       | Total number of elements                     | 12
.dtype      | Data type of array elements                  | int32
.itemsize   | Size of one element in bytes                  | 4
.nbytes     | Total memory (in bytes) consumed by elements | 48
.T          | Transposed view of the array                 | Flips rows/cols
.data       | Buffer containing actual data                | <memory>


In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize, "bytes")
print("Total bytes:", arr.nbytes)
print("Transposed:\n", arr.T)


Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Data type: int64
Item size: 8 bytes
Total bytes: 48
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


Flatten vs ravel

Method     | Description                                                                 | Returns Copy or View | Example
-----------|------------------------------------------------------------------------------|----------------------|----------------------------------
flatten()  | Returns a new 1D array copy of the original array's data                     | Copy                 | arr.flatten()
ravel()    | Returns a flattened view of the array when possible; otherwise returns copy | View (if possible)   | arr.ravel()


In [5]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

flat_arr = arr.flatten()  # Copy
ravel_arr = arr.ravel()   # View

# Modify ravel array to see effect on original
ravel_arr[0] = 99

print("Original array:\n", arr)  # Notice change if ravel() gave view
print("Flattened array:", flat_arr)
print("Ravelled array:", ravel_arr)


Original array:
 [[99  2]
 [ 3  4]]
Flattened array: [1 2 3 4]
Ravelled array: [99  2  3  4]


      y
      ↑
      |
      |      ● (x, y)
      |
      +--------------→ x
     (0,0)
2D array as a co-ordinate not as a matrix